<%
/* ### Generated by AIDesigner 3.7.1.22 ### */
%>

<%@ page language="java" import="java.sql.*,java.io.*,java.text.*" %>
<%@ page contentType="text/plain; charset=euc-kr" %>

<%
Object[] userObj = null;
ReportHandler handler = new ReportHandler(request,response,userObj);
handler.service(out);
%>

<%!
class ReportHandler{
	//공통 변수 선언
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private String isEmpty="";		//빈 문자열 비교에 사용

	private HttpServletRequest request;
	private HttpServletResponse response;
	private JspWriter out;

	//-----데이터 변수 선언-----
	String sheet10_A1;
	String sheet10_A3;
	String sheet10_A4;
	String sheet10_B4;
	String sheet10_C4;
	String sheet10_D4;
	String sheet10_E4;
	String sheet10_F4;
	String sheet10_G4;
	String sheet10_H4;
	String sheet10_I4;
	String sheet10_J4;
	String sheet10_K4;
	String sheet10_E5;
	String sheet10_F5;
	String sheet10_G5;
	String sheet10_H5;
	String sheet10_A6;
	double sheet10_D6;
	double sheet10_E6;
	double sheet10_F6;
	double sheet10_G6;
	double sheet10_H6;
	double sheet10_I6;
	double sheet10_J6;
	double sheet10_K6;
	long sheet10_A7;
	String sheet10_B7;
	String sheet10_C7;
	double sheet10_D7;
	double sheet10_E7;
	double sheet10_F7;
	double sheet10_G7;
	double sheet10_H7;
	double sheet10_I7;
	double sheet10_J7;
	double sheet10_K7;

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_DUNET;		//DSN DUNET Connection 객체
	private java.sql.Statement stat_totSum;		//ResultSet totSum 객체를 생성하기 위한 Statement 객체
	private ResultSet totSum;		//ResultSet totSum 객체
	private java.sql.Statement stat_list;		//ResultSet list 객체를 생성하기 위한 Statement 객체
	private ResultSet list;		//ResultSet list 객체

	//-----SQL 변수 선언-----
	private String sql_totSum;		//ResultSet totSum 객체를 생성하기 위한 쿼리문 저장
	private String sql_list;		//ResultSet list 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet totSum 객체에서 필드 값을 받는 쿼리 필드 변수
	private double totSum_STU_CNT;
	private double totSum_TSTEP;
	private double totSum_BUMWI_CNT;
	private double totSum_QUS_CNT;
	private double totSum_ANS_CNT;
	private double totSum_REP_CNT;
	private double totSum_EXAM_CNT;
	private double totSum_REPORT_AVG;

	//ResultSet list 객체에서 필드 값을 받는 쿼리 필드 변수
	private String list_GRCODE;
	private String list_GRSEQ;
	private String list_SUBJ;
	private double list_CLASSNO;
	private String list_CLASSNM;
	private String list_TOTURLIST;
	private double list_STU_CNT;
	private double list_TSTEP;
	private double list_BUMWI_CNT;
	private double list_QUS_CNT;
	private double list_ANS_CNT;
	private double list_REP_CNT;
	private double list_REPORT_AVG;
	private double list_EXAM_CNT;

	//파라미터 변수 선언
	String p_startstep_Param;
	String p_endstep_Param;
	String p_subj_Param;
	String p_grcode_Param;
	String p_grseq_Param;

	//ReportHandler 생성자 함수
	ReportHandler(HttpServletRequest request,HttpServletResponse response,Object[] userObj){
		this.request=request;
		this.response=response;
		this.userObj=userObj;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			this.out=out;
			nMaxPage=0;    //nMaxPage 초기화

			//스크립트 헤더 함수 호출
			getScriptHeader("A4", "2100x2970", "9", "VERTICAL");

			//파라미터 설정 함수 호출
			setParam();

			//고정 데이터 초기화 함수 호출
			initConstVarient();

			//Connection 및 Statement 객체 생성 함수 호출
			createConnAndStateObject();

			//쿼리문 초기화 함수 호출
			initSQLConst();

			//쉬트 함수 호출
			//SHEET=Sheet1   FRAME=0 함수 호출
			executeSheet10();

			//---------------스크립트 종료---------------
			out.print("--SCRIPT_END--\r");
		}catch(Exception e){    //catch 구문
			out.print(e);
			out.print("AI!REPORT JSP ERROR!!!!\r");
		}finally{    //finally 구문
			try{    //finally try 구문
				//DataSet Close
				if(list!=null) list.close();
				if(stat_list!=null) stat_list.close();
				if(totSum!=null) totSum.close();
				if(stat_totSum!=null) stat_totSum.close();
				if(conn_DUNET!=null) conn_DUNET.close();
			}catch(Exception e){    //finally catch 구문
			}    //end finally try
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		initSheetVariant(41, 99, 546, 781, true);

		//시작 페이지 번호 출력
		out.print("-- " + nPageNum + " PAGE --\r");

		//밴드 함수 호출
		getScriptFromtitle(true, true);    //머리글 밴드 호출
		getScriptFromfoot(true, true);    //바닥글 밴드 호출
		getScriptFromlist(true);    //반복 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----title HeaderBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : title
	//----밴드 종류 : 머리글 밴드
	//----bIsFrist : 쉬트 함수에서 최초로 호출될 때 true, 페이지 스킵 함수에서 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromtitle(boolean bIsFirst, boolean bIsPrint) throws Exception{
		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 함수 호출
			writeScripttitle();
		}   //end if(bIsPrint)
	}

	//----foot FooterBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : foot
	//----밴드 종류 : 바닥글 밴드
	//----bIsFrist : 쉬트 함수에서 최초로 호출될 때 true, 페이지 스킵 함수에서 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromfoot(boolean bIsFirst, boolean bIsPrint) throws Exception{
		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 함수 호출
			writeScriptfoot();
		}   //end if(bIsPrint)
	}

	//----header RepeatHeader Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : header
	//----밴드 종류 : 반복 헤더
	//----bIsFrist : 반복 밴드 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromheader(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=50;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet totSum 객체의 생성
			if(totSum==null){
				totSum = stat_totSum.executeQuery(sql_totSum);
			}else{
				totSum.beforeFirst();
			}

			//데이터 fetch
			if(totSum.next()){
				setFieldVariableFromtotSum();	//ResultSet totSum에서 필드 값 설정
			}else{
				setFieldInitFromtotSum();	//ResultSet totSum의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet10_F4="";
			sheet10_D6=0;
			sheet10_E6=0;
			sheet10_F6=0;
			sheet10_G6=0;
			sheet10_H6=0;
			sheet10_I6=0;
			sheet10_J6=0;
			sheet10_K6=0;

			//데이터 변수 할당
			sheet10_F4=p_startstep_Param + "%~"+ p_endstep_Param + "%";
			sheet10_D6=totSum_STU_CNT;
			sheet10_E6=totSum_TSTEP;
			sheet10_F6=totSum_BUMWI_CNT;
			sheet10_G6=totSum_QUS_CNT;
			sheet10_H6=totSum_ANS_CNT;
			sheet10_I6=totSum_REP_CNT;
			sheet10_J6=totSum_EXAM_CNT;
			sheet10_K6=totSum_REPORT_AVG;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptheader();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----list RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : list
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromlist(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A7=0L;
		sheet10_B7="";
		sheet10_C7="";
		sheet10_D7=0;
		sheet10_E7=0;
		sheet10_F7=0;
		sheet10_G7=0;
		sheet10_H7=0;
		sheet10_I7=0;
		sheet10_J7=0;
		sheet10_K7=0;

		//DataSet 객체 생성
		//ResultSet list 객체의 생성
		if(list==null){
			list = stat_list.executeQuery(sql_list);
		}else{
			list.beforeFirst();
		}

		while(list.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFromlist();	//RecordSet list에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
				//반복 헤더 호출 및 조건 플래그 초기화
				getScriptFromheader(bIsFirst, true);	//반복 헤더 호출
			}   //end if(bIsFirst)

			//데이터 변수 할당
			sheet10_A7=COUNT(sheet10_A7);
			sheet10_B7=list_CLASSNM;
			sheet10_C7=list_TOTURLIST;
			sheet10_D7=list_STU_CNT;
			sheet10_E7=list_TSTEP;
			sheet10_F7=list_BUMWI_CNT;
			sheet10_G7=list_QUS_CNT;
			sheet10_H7=list_ANS_CNT;
			sheet10_I7=list_REP_CNT;
			sheet10_J7=list_REPORT_AVG;
			sheet10_K7=list_EXAM_CNT;

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//페이지 스킵 함수 호출
					pageSkip(10);

					//반복 헤더 및 부모 반복단위 호출
					getScriptFromheader(false, true);	//반복 헤더 호출
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptlist();

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end
	}

	//-----스크립트 출력 함수-----
	//----title 스크립트 문 출력 함수----
	private void writeScripttitle( ) throws Exception{
		//스크립트문 생성
		out.print("^PRINT(41,41,504,1,16,0/,돋움체,RGB[0,0,0],BOLD, , ,NONE,38,1)");
		out.println(sheet10_A1+"\r");
	}

	//----foot 스크립트 문 출력 함수----
	private void writeScriptfoot( ) throws Exception{
		//스크립트문 생성
		out.print("^PRINT(41,781,504,1,11,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_A3+"\r");
	}

	//----header 스크립트 문 출력 함수----
	private void writeScriptheader( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos)+",30,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos)+",30,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_A4+"\r");
		out.println("^CELLBG("+(nXCurPos+30)+","+(nYCurPos)+",26,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+30)+","+(nYCurPos)+",26,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_B4+"\r");
		out.println("^CELLBG("+(nXCurPos+56)+","+(nYCurPos)+",47,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+56)+","+(nYCurPos)+",47,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_C4+"\r");
		out.println("^CELLBG("+(nXCurPos+103)+","+(nYCurPos)+",49,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+103)+","+(nYCurPos)+",49,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_D4+"\r");
		out.println("^CELLBG("+(nXCurPos+152)+","+(nYCurPos)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+152)+","+(nYCurPos)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_E4+"\r");
		out.println("^CELLBG("+(nXCurPos+202)+","+(nYCurPos)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+202)+","+(nYCurPos)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_F4+"\r");
		out.println("^CELLBG("+(nXCurPos+252)+","+(nYCurPos)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+252)+","+(nYCurPos)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_G4+"\r");
		out.println("^CELLBG("+(nXCurPos+302)+","+(nYCurPos)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+302)+","+(nYCurPos)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_H4+"\r");
		out.println("^CELLBG("+(nXCurPos+352)+","+(nYCurPos)+",55,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+352)+","+(nYCurPos)+",55,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_I4+"\r");
		out.println("^CELLBG("+(nXCurPos+407)+","+(nYCurPos)+",44,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+407)+","+(nYCurPos)+",44,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_J4+"\r");
		out.println("^CELLBG("+(nXCurPos+451)+","+(nYCurPos)+",53,30,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,30,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,30,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,30,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,30,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+451)+","+(nYCurPos)+",53,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,30,1)");
		out.println(sheet10_K4+"\r");
		out.println("^CELLBG("+(nXCurPos+152)+","+(nYCurPos+15)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+152)+","+(nYCurPos+15)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_E5+"\r");
		out.println("^CELLBG("+(nXCurPos+202)+","+(nYCurPos+15)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+202)+","+(nYCurPos+15)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_F5+"\r");
		out.println("^CELLBG("+(nXCurPos+252)+","+(nYCurPos+15)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+252)+","+(nYCurPos+15)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_G5+"\r");
		out.println("^CELLBG("+(nXCurPos+302)+","+(nYCurPos+15)+",50,15,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+15)+",50,15,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+302)+","+(nYCurPos+15)+",50,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,15,1)");
		out.println(sheet10_H5+"\r");
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos+30)+",103,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+30)+",103,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+30)+",103,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+30)+",103,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+30)+",103,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos+30)+",103,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_A6+"\r");
		out.println("^CELLBG("+(nXCurPos+103)+","+(nYCurPos+30)+",49,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos+30)+",49,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos+30)+",49,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos+30)+",49,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos+30)+",49,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+103)+","+(nYCurPos+30)+",49,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_D6+"\r");
		out.println("^CELLBG("+(nXCurPos+152)+","+(nYCurPos+30)+",50,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+152)+","+(nYCurPos+30)+",50,1,10,1/1/2,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_E6+"\r");
		out.println("^CELLBG("+(nXCurPos+202)+","+(nYCurPos+30)+",50,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+202)+","+(nYCurPos+30)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_F6+"\r");
		out.println("^CELLBG("+(nXCurPos+252)+","+(nYCurPos+30)+",50,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+252)+","+(nYCurPos+30)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_G6+"\r");
		out.println("^CELLBG("+(nXCurPos+302)+","+(nYCurPos+30)+",50,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos+30)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+302)+","+(nYCurPos+30)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_H6+"\r");
		out.println("^CELLBG("+(nXCurPos+352)+","+(nYCurPos+30)+",55,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos+30)+",55,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos+30)+",55,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos+30)+",55,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos+30)+",55,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+352)+","+(nYCurPos+30)+",55,1,10,1/0/2,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_I6+"\r");
		out.println("^CELLBG("+(nXCurPos+407)+","+(nYCurPos+30)+",44,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos+30)+",44,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos+30)+",44,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos+30)+",44,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos+30)+",44,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+407)+","+(nYCurPos+30)+",44,1,10,1/0/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_J6+"\r");
		out.println("^CELLBG("+(nXCurPos+451)+","+(nYCurPos+30)+",53,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos+30)+",53,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos+30)+",53,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos+30)+",53,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos+30)+",53,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+451)+","+(nYCurPos+30)+",53,1,10,1/0/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_K6+"\r");
	}

	//----list 스크립트 문 출력 함수----
	private void writeScriptlist( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",30,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos)+",30,1,10,1/0/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_A7+"\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+30)+","+(nYCurPos)+",26,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+30)+","+(nYCurPos)+",26,1,10,5/\"반\"*,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_B7+"\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+56)+","+(nYCurPos)+",47,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+56)+","+(nYCurPos)+",47,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C7+"\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+103)+","+(nYCurPos)+",49,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+103)+","+(nYCurPos)+",49,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_D7+"\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+152)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+152)+","+(nYCurPos)+",50,1,10,1/1/2,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_E7+"\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+202)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+202)+","+(nYCurPos)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_F7+"\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+252)+","+(nYCurPos)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_G7+"\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+302)+","+(nYCurPos)+",50,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+302)+","+(nYCurPos)+",50,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_H7+"\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+352)+","+(nYCurPos)+",55,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+352)+","+(nYCurPos)+",55,1,10,1/1/2,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_I7+"\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+407)+","+(nYCurPos)+",44,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+407)+","+(nYCurPos)+",44,1,10,1/0/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_J7+"\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+451)+","+(nYCurPos)+",53,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+451)+","+(nYCurPos)+",53,1,10,1/0/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_K7+"\r");
	}

	//파라미터 설정 함수
	private void setParam(){
		p_startstep_Param=toKor(GetB(request.getParameter("p_startstep")));
		p_endstep_Param=toKor(GetB(request.getParameter("p_endstep")));
		p_subj_Param=toKor(GetB(request.getParameter("p_subj")));
		p_grcode_Param=toKor(GetB(request.getParameter("p_grcode")));
		p_grseq_Param=toKor(GetB(request.getParameter("p_grseq")));
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//DUNET Connection 객체 생성
		Class.forName("oracle.jdbc.driver.OracleDriver");
		conn_DUNET = DriverManager.getConnection("jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.12.203)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.12.204)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=off))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=LOTI)))","inchlms","fhxl21");stat_totSum=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		stat_list=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst(){
		sql_totSum = "SELECT sum(stu_cnt) as stu_cnt ";
		sql_totSum = sql_totSum + "     , round(avg(tstep),2) as tstep ";
		sql_totSum = sql_totSum + "     , sum(bumwi_cnt) as bumwi_cnt ";
		sql_totSum = sql_totSum + "     , sum(qus_cnt) as qus_cnt ";
		sql_totSum = sql_totSum + "     , sum(ans_cnt) as ans_cnt ";
		sql_totSum = sql_totSum + "     , sum(rep_cnt) as rep_cnt ";
		sql_totSum = sql_totSum + "     , sum(exam_cnt) as exam_cnt ";
		sql_totSum = sql_totSum + "     , round(avg(report_avg),2) as report_avg ";
		sql_totSum = sql_totSum + "FROM ( ";
		sql_totSum = sql_totSum + "SELECT gsl.grcode ";
		sql_totSum = sql_totSum + "     , gsl.grseq ";
		sql_totSum = sql_totSum + "     , gsl.subj ";
		sql_totSum = sql_totSum + "     , gsl.classno ";
		sql_totSum = sql_totSum + "     , (SELECT classnm  ";
		sql_totSum = sql_totSum + "          FROM tb_subjclass  ";
		sql_totSum = sql_totSum + "         WHERE grcode = gsl.grcode  ";
		sql_totSum = sql_totSum + "         AND grseq    = gsl.grseq  ";
		sql_totSum = sql_totSum + "         AND subj     = gsl.subj  ";
		sql_totSum = sql_totSum + "         AND classno  = gsl.classno) classnm ";
		sql_totSum = sql_totSum + "     , getTutorNmList(gsl.grcode, gsl.grseq, gsl.subj, gsl.classno) toturlist ";
		sql_totSum = sql_totSum + "     , gsl.stu_cnt ";
		sql_totSum = sql_totSum + "     , nvl(gsl.tstep,0) tstep ";
		sql_totSum = sql_totSum + "     , nvl(gsl.bumwi_cnt,0) bumwi_cnt ";
		sql_totSum = sql_totSum + "     , nvl(gsq.qus_cnt,0) qus_cnt ";
		sql_totSum = sql_totSum + "     , nvl(gsq.ans_cnt,0) ans_cnt  ";
		sql_totSum = sql_totSum + "     , nvl(grp.rep_cnt,0) rep_cnt ";
		sql_totSum = sql_totSum + "     , nvl(grp.report_avg,0) report_avg ";
		sql_totSum = sql_totSum + "     , (SELECT count(distinct ptype) exam_cnt  ";
		sql_totSum = sql_totSum + "          FROM tb_exresult  ";
		sql_totSum = sql_totSum + "         WHERE grcode = gsl.grcode  ";
		sql_totSum = sql_totSum + "         AND grseq    = gsl.grseq  ";
		sql_totSum = sql_totSum + "         AND subj     = gsl.subj) exam_cnt  ";
		sql_totSum = sql_totSum + " FROM ( SELECT grcode ";
		sql_totSum = sql_totSum + "             , grseq ";
		sql_totSum = sql_totSum + "	     , subj ";
		sql_totSum = sql_totSum + "	     , classno ";
		sql_totSum = sql_totSum + "	     , count(*) stu_cnt ";
		sql_totSum = sql_totSum + "	     , sum(case when nvl(tstep,0) >=" + p_startstep_Param + " AND nvl(tstep,0) <=" + p_endstep_Param + " then 1 end) bumwi_cnt ";
		sql_totSum = sql_totSum + "	     , round(avg(tstep),2) tstep ";
		sql_totSum = sql_totSum + "	     , avg(quizstep) quizstep ";
		sql_totSum = sql_totSum + "          FROM tb_stu_lec ";
		sql_totSum = sql_totSum + "	  GROUP BY grcode, grseq, subj, classno ) gsl ";
		sql_totSum = sql_totSum + "    , ( SELECT grcode ";
		sql_totSum = sql_totSum + "             , grseq ";
		sql_totSum = sql_totSum + "	     , subj ";
		sql_totSum = sql_totSum + "	     , classno ";
		sql_totSum = sql_totSum + "	     , count(*) rep_cnt ";
		sql_totSum = sql_totSum + "	     , round(avg(submit_point),2) report_avg ";
		sql_totSum = sql_totSum + "          FROM tb_report_submit ";
		sql_totSum = sql_totSum + "	  GROUP BY grcode, grseq, subj, classno ) grp ";
		sql_totSum = sql_totSum + "    , ( SELECT grcode ";
		sql_totSum = sql_totSum + "             , grseq ";
		sql_totSum = sql_totSum + "	     , subj ";
		sql_totSum = sql_totSum + "	     , classno ";
		sql_totSum = sql_totSum + "	     , sum(decode(depth,1,1)) qus_cnt ";
		sql_totSum = sql_totSum + "	     , sum(decode(depth,2,1)) ans_cnt ";
		sql_totSum = sql_totSum + "          FROM tb_subjqna ";
		sql_totSum = sql_totSum + "	  GROUP BY grcode, grseq, subj, classno ) gsq ";
		sql_totSum = sql_totSum + " WHERE gsl.grcode = grp.grcode(+) ";
		sql_totSum = sql_totSum + " AND gsl.grseq    = grp.grseq(+) ";
		sql_totSum = sql_totSum + " AND gsl.subj     = grp.subj(+) ";
		sql_totSum = sql_totSum + " AND gsl.classno  = grp.classno(+) ";
		sql_totSum = sql_totSum + " AND gsl.grcode   = gsq.grcode(+) ";
		sql_totSum = sql_totSum + " AND gsl.grseq    = gsq.grseq(+) ";
		sql_totSum = sql_totSum + " AND gsl.subj     = gsq.subj(+) ";
		sql_totSum = sql_totSum + " AND gsl.classno  = gsq.classno(+) ";
		sql_totSum = sql_totSum + " AND gsl.subj     = '" + p_subj_Param + "' ";
		sql_totSum = sql_totSum + " AND gsl.grcode   = '" + p_grcode_Param + "' ";
		sql_totSum = sql_totSum + " AND gsl.grseq    = '" + p_grseq_Param + "' ";
		sql_totSum = sql_totSum + " ORDER BY gsl.grcode, gsl.grseq, gsl.subj, gsl.classno )";
		sql_list = "SELECT gsl.grcode ";
		sql_list = sql_list + "     , gsl.grseq ";
		sql_list = sql_list + "     , gsl.subj ";
		sql_list = sql_list + "     , gsl.classno ";
		sql_list = sql_list + "     , (SELECT classnm  ";
		sql_list = sql_list + "          FROM tb_subjclass  ";
		sql_list = sql_list + "         WHERE grcode = gsl.grcode  ";
		sql_list = sql_list + "         AND grseq    = gsl.grseq  ";
		sql_list = sql_list + "         AND subj     = gsl.subj  ";
		sql_list = sql_list + "         AND classno  = gsl.classno) classnm ";
		sql_list = sql_list + "     , getTutorNmList(gsl.grcode, gsl.grseq, gsl.subj, gsl.classno) toturlist ";
		sql_list = sql_list + "     , gsl.stu_cnt ";
		sql_list = sql_list + "     , nvl(gsl.tstep,0) tstep ";
		sql_list = sql_list + "     , nvl(gsl.bumwi_cnt,0) bumwi_cnt ";
		sql_list = sql_list + "     , nvl(gsq.qus_cnt,0) qus_cnt ";
		sql_list = sql_list + "     , nvl(gsq.ans_cnt,0) ans_cnt  ";
		sql_list = sql_list + "     , nvl(grp.rep_cnt,0) rep_cnt ";
		sql_list = sql_list + "     , nvl(grp.report_avg,0) report_avg ";
		sql_list = sql_list + "     , (SELECT count(distinct ptype) exam_cnt  ";
		sql_list = sql_list + "          FROM tb_exresult  ";
		sql_list = sql_list + "         WHERE grcode = gsl.grcode  ";
		sql_list = sql_list + "         AND grseq    = gsl.grseq  ";
		sql_list = sql_list + "         AND subj     = gsl.subj) exam_cnt  ";
		sql_list = sql_list + " FROM ( SELECT grcode ";
		sql_list = sql_list + "             , grseq ";
		sql_list = sql_list + "	     , subj ";
		sql_list = sql_list + "	     , classno ";
		sql_list = sql_list + "	     , count(*) stu_cnt ";
		sql_list = sql_list + "	     , sum(case when nvl(tstep,0) >=" + p_startstep_Param + " AND nvl(tstep,0) <=" + p_endstep_Param + " then 1 end) bumwi_cnt ";
		sql_list = sql_list + "	     , round(avg(tstep),2) tstep ";
		sql_list = sql_list + "	     , avg(quizstep) quizstep ";
		sql_list = sql_list + "          FROM tb_stu_lec ";
		sql_list = sql_list + "	  GROUP BY grcode, grseq, subj, classno ) gsl ";
		sql_list = sql_list + "    , ( SELECT grcode ";
		sql_list = sql_list + "             , grseq ";
		sql_list = sql_list + "	     , subj ";
		sql_list = sql_list + "	     , classno ";
		sql_list = sql_list + "	     , count(*) rep_cnt ";
		sql_list = sql_list + "	     , round(avg(submit_point),2) report_avg ";
		sql_list = sql_list + "          FROM tb_report_submit ";
		sql_list = sql_list + "	  GROUP BY grcode, grseq, subj, classno ) grp ";
		sql_list = sql_list + "    , ( SELECT grcode ";
		sql_list = sql_list + "             , grseq ";
		sql_list = sql_list + "	     , subj ";
		sql_list = sql_list + "	     , classno ";
		sql_list = sql_list + "	     , sum(decode(depth,1,1)) qus_cnt ";
		sql_list = sql_list + "	     , sum(decode(depth,2,1)) ans_cnt ";
		sql_list = sql_list + "          FROM tb_subjqna ";
		sql_list = sql_list + "	  GROUP BY grcode, grseq, subj, classno ) gsq ";
		sql_list = sql_list + " WHERE gsl.grcode = grp.grcode(+) ";
		sql_list = sql_list + " AND gsl.grseq    = grp.grseq(+) ";
		sql_list = sql_list + " AND gsl.subj     = grp.subj(+) ";
		sql_list = sql_list + " AND gsl.classno  = grp.classno(+) ";
		sql_list = sql_list + " AND gsl.grcode   = gsq.grcode(+) ";
		sql_list = sql_list + " AND gsl.grseq    = gsq.grseq(+) ";
		sql_list = sql_list + " AND gsl.subj     = gsq.subj(+) ";
		sql_list = sql_list + " AND gsl.classno  = gsq.classno(+) ";
		sql_list = sql_list + " AND gsl.subj     = '" + p_subj_Param + "' ";
		sql_list = sql_list + " AND gsl.grcode   = '" + p_grcode_Param + "' ";
		sql_list = sql_list + " AND gsl.grseq    = '" + p_grseq_Param + "' ";
		sql_list = sql_list + " ORDER BY gsl.grcode, gsl.grseq, gsl.subj, gsl.classno";
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet totSum 객체에서 필드 값 설정 함수
	private void setFieldVariableFromtotSum() throws Exception{
		totSum_STU_CNT=totSum.getDouble(1);
		totSum_TSTEP=totSum.getDouble(2);
		totSum_BUMWI_CNT=totSum.getDouble(3);
		totSum_QUS_CNT=totSum.getDouble(4);
		totSum_ANS_CNT=totSum.getDouble(5);
		totSum_REP_CNT=totSum.getDouble(6);
		totSum_EXAM_CNT=totSum.getDouble(7);
		totSum_REPORT_AVG=totSum.getDouble(8);
	}

	//ResultSet totSum 객체의 필드 값 초기화 함수
	private void setFieldInitFromtotSum(){
		totSum_STU_CNT=0;
		totSum_TSTEP=0;
		totSum_BUMWI_CNT=0;
		totSum_QUS_CNT=0;
		totSum_ANS_CNT=0;
		totSum_REP_CNT=0;
		totSum_EXAM_CNT=0;
		totSum_REPORT_AVG=0;
	}

	//ResultSet list 객체에서 필드 값 설정 함수
	private void setFieldVariableFromlist() throws Exception{
		list_GRCODE=GetB(list.getString(1));
		list_GRSEQ=GetB(list.getString(2));
		list_SUBJ=GetB(list.getString(3));
		list_CLASSNO=list.getDouble(4);
		list_CLASSNM=GetB(list.getString(5));
		list_TOTURLIST=GetB(list.getString(6));
		list_STU_CNT=list.getDouble(7);
		list_TSTEP=list.getDouble(8);
		list_BUMWI_CNT=list.getDouble(9);
		list_QUS_CNT=list.getDouble(10);
		list_ANS_CNT=list.getDouble(11);
		list_REP_CNT=list.getDouble(12);
		list_REPORT_AVG=list.getDouble(13);
		list_EXAM_CNT=list.getDouble(14);
	}

	//ResultSet list 객체의 필드 값 초기화 함수
	private void setFieldInitFromlist(){
		list_GRCODE="";
		list_GRSEQ="";
		list_SUBJ="";
		list_CLASSNO=0;
		list_CLASSNM="";
		list_TOTURLIST="";
		list_STU_CNT=0;
		list_TSTEP=0;
		list_BUMWI_CNT=0;
		list_QUS_CNT=0;
		list_ANS_CNT=0;
		list_REP_CNT=0;
		list_REPORT_AVG=0;
		list_EXAM_CNT=0;
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarient(){
		sheet10_A1="반별 학습현황통계";
		sheet10_A3="#PAGE / #TOTALPAGE";
		sheet10_A4="번호";
		sheet10_B4="반";
		sheet10_C4="강사명";
		sheet10_D4="교육생수";
		sheet10_E4="평균진도";
		sheet10_G4="질문건수";
		sheet10_H4="답변건수";
		sheet10_I4="과제물제출";
		sheet10_J4="평가건수";
		sheet10_K4="과제물평균";
		sheet10_E5="(%)";
		sheet10_F5="교육생수";
		sheet10_G5="(학생)";
		sheet10_H5="(강사";
		sheet10_A6="총        계";
	}

	//-----페이지 스킵 관련 함수-----
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		out.print("-- " + nPageNum + " PAGE --\r");

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			getScriptFromtitle(false, true);		//머리글 밴드 호출
			getScriptFromfoot(false, true);		//바닥글 밴드 호출
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//-----공통 함수 선언-----
	private void getScriptHeader(String paper, String size, String value, String orient) throws Exception{
		out.print("--SCRIPT_START31--\r");
		out.print("PAPER=" + paper + "\r");
		out.print("PAPER_SIZE=" + size + "\r");
		out.print("PAPER_SETTING_VALUE=" + value + "\r");
		out.print("ORIENTATION=" + orient + "\r");
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient) throws Exception{
		out.print("--PAPER_INFO--\r");
		out.print("PAPER=" + paper + "\r");
		out.print("PAPER_SIZE=" + size + "\r");
		out.print("PAPER_SETTING_VALUE=" + value + "\r");
		out.print("ORIENTATION=" + orient + "\r");
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}
	private long MAX(long maxV, long maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		while(strAll.indexOf(strSrc) != -1) {
			strAll = strAll.substring(0, strAll.indexOf(strSrc)) + strDest + strAll.substring(strAll.indexOf(strSrc) + strSrc.length(), strAll.length());
		}
		return strAll;
	}

	private String toDate() {
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("8859_1"), "KSC5601");
		}catch(Exception e){return en;}
	}
}
%>
