<%
/* ### Generated by AIDesigner 3.7.1.22 ### */
%>

<%@ page language="java" import="java.sql.*,java.io.*,java.text.*" %>
<%@ page contentType="text/plain; charset=euc-kr" %>

<%
Object[] userObj = null;
ReportHandler handler = new ReportHandler(request,response,userObj);
handler.service(out);
%>

<%!
class ReportHandler{
	//공통 변수 선언
	private Object[] userObj = null;
	private int nStartPage;		//각 쉬트별 시작 페이지 저장
	private int nMaxPage;		//한 쉬트가 실행된 후 생성된 최대 페이지 번호 저장
	private int nPageNum;		//현재 페이지 번호
	private int nYStartPos;		//쉬트에서 Y 시작 좌표
	private int nYEndPos;		//쉬트에서 Y 끝 좌표
	private int nYCurPos;		//현재 Y 좌표
	private int nYSavePos;		//연결된 멀티 프레임 쉬트에서 시작 Y 좌표 저장
	private int nYLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 Y 좌표 저장
	private int nXStartPos;		//쉬트에서 X 시작 좌표
	private int nXEndPos;		//쉬트에서 X 끝 좌표
	private int nXCurPos;		//현재 X 좌표
	private int nXSavePos;		//연결된 멀티 프레임 쉬트에서 시작 X 좌표 저장
	private int  nXLastPos;		//연결된 멀티 프레임 쉬트에서 각 프레임의 마지막 X 좌표 저장
	private boolean bIsBeforePageSkip;		//조건 밴드에서 페이지 넘기기 여부 판단
	private int nLoopRef;		//절대 양식에서 루프 참조 변수
	private String isEmpty="";		//빈 문자열 비교에 사용

	private HttpServletRequest request;
	private HttpServletResponse response;
	private JspWriter out;

	//-----데이터 변수 선언-----
	String sheet10_A1;
	String sheet10_A2;
	String sheet10_B2;
	String sheet10_D2;
	String sheet10_E2;
	String sheet10_A3_Buf;
	int sheet10_A3_YPos;
	boolean sheet10_A3_Flag;
	String sheet10_A3;
	String sheet10_B3;
	String sheet10_C3;
	boolean bEnabledVirtualMerge_info_goal;
	String sheet10_A4_Buf;
	int sheet10_A4_YPos;
	boolean sheet10_A4_Flag;
	String sheet10_A4;
	String sheet10_B4;
	String sheet10_C4;
	boolean bEnabledVirtualMerge_info_target;
	String sheet10_A5_Buf;
	int sheet10_A5_YPos;
	boolean sheet10_A5_Flag;
	String sheet10_A5;
	String sheet10_B5;
	String sheet10_C5;
	boolean bEnabledVirtualMerge_info_inwon;
	String sheet10_A6_Buf;
	int sheet10_A6_YPos;
	boolean sheet10_A6_Flag;
	String sheet10_A6;
	String sheet10_B6;
	String sheet10_C6;
	boolean bEnabledVirtualMerge_info_gigan;
	String sheet10_A7_Buf;
	int sheet10_A7_YPos;
	boolean sheet10_A7_Flag;
	String sheet10_A7;
	String sheet10_B7;
	String sheet10_C7;
	boolean bEnabledVirtualMerge_info_yunyong;
	String sheet20_A1;
	String sheet20_C2;
	String sheet20_D2;
	String sheet20_E2;
	String sheet20_F2;
	String sheet20_I2;
	String sheet20_F3;
	String sheet20_G3;
	String sheet20_H3;
	String sheet20_C4;
	String sheet20_D4;
	String sheet20_E4;
	String sheet20_F4;
	String sheet20_G4;
	String sheet20_H4;
	String sheet20_I4;
	String sheet20_C5;
	String sheet20_D5;
	String sheet20_E5;
	String sheet20_F5;
	String sheet20_G5;
	String sheet20_H5;
	String sheet20_I5;
	String sheet30_A1;
	String sheet30_B1;
	String sheet30_C1;
	String sheet30_F1;
	String sheet30_C2;
	String sheet30_D2;
	String sheet30_E2;
	String sheet30_A3;
	double sheet30_C3;
	double sheet30_D3;
	double sheet30_E3;
	String sheet30_B4;
	double sheet30_C4;
	double sheet30_D4;
	double sheet30_E4;
	int[] nAutoHeight_detail=new int[1];
	String sheet30_A5_Buf;
	int sheet30_A5_YPos;
	boolean sheet30_A5_Flag;
	String sheet30_A5;
	String sheet30_B5;
	double sheet30_C5;
	double sheet30_D5;
	double sheet30_E5;
	String sheet30_F5;
	boolean bEnabledVirtualMerge_detail;

	//-----Connection, Statement, ResultSet 객체 선언-----
	private Connection conn_DUNET;		//DSN DUNET Connection 객체
	private java.sql.Statement stat_totSum;		//ResultSet totSum 객체를 생성하기 위한 Statement 객체
	private ResultSet totSum;		//ResultSet totSum 객체
	private java.sql.Statement stat_detail;		//ResultSet detail 객체를 생성하기 위한 Statement 객체
	private ResultSet detail;		//ResultSet detail 객체
	private java.sql.Statement stat_master;		//ResultSet master 객체를 생성하기 위한 Statement 객체
	private ResultSet master;		//ResultSet master 객체
	private java.sql.Statement stat_info;		//ResultSet info 객체를 생성하기 위한 Statement 객체
	private ResultSet info;		//ResultSet info 객체
	private java.sql.Statement stat_grcodenm;		//ResultSet grcodenm 객체를 생성하기 위한 Statement 객체
	private ResultSet grcodenm;		//ResultSet grcodenm 객체

	//-----SQL 변수 선언-----
	private String sql_totSum;		//ResultSet totSum 객체를 생성하기 위한 쿼리문 저장
	private String sql_detail;		//ResultSet detail 객체를 생성하기 위한 쿼리문 저장
	private String sql_master;		//ResultSet master 객체를 생성하기 위한 쿼리문 저장
	private String sql_info;		//ResultSet info 객체를 생성하기 위한 쿼리문 저장
	private String sql_grcodenm;		//ResultSet grcodenm 객체를 생성하기 위한 쿼리문 저장

	//-----쿼리 필드 변수 선언-----
	//ResultSet totSum 객체에서 필드 값을 받는 쿼리 필드 변수
	private double totSum_TOT_TITLE1_SUB1;
	private double totSum_TOT_TITLE1_SUB2;
	private double totSum_TOT_TITLE1_SUB3;

	//ResultSet detail 객체에서 필드 값을 받는 쿼리 필드 변수
	private String detail_GRCODE;
	private String detail_YEAR;
	private String detail_GUBUN;
	private double detail_ANNAE_SEQ;
	private String detail_ANNAE_TITLE;
	private double detail_TITLE1_SUB1;
	private double detail_TITLE1_SUB2;
	private double detail_TITLE1_SUB3;
	private String detail_TITLE1_SUB4;

	//ResultSet master 객체에서 필드 값을 받는 쿼리 필드 변수
	private String master_ANNAE_GUBUN;
	private double master_TOT_TITLE1_SUB1;
	private double master_TOT_TITLE1_SUB2;
	private double master_TOT_TITLE1_SUB3;
	private String master_GUBUN;

	//ResultSet info 객체에서 필드 값을 받는 쿼리 필드 변수
	private String info_GRCODE;
	private String info_YEAR;
	private String info_GOAL;
	private String info_TARGET;
	private String info_INWON;
	private String info_GIGAN;
	private String info_SIGANGE;
	private String info_SIBUNYA;
	private String info_SISOGE;
	private String info_SICOMMON;
	private String info_SIJUNMUN;
	private String info_SIETC;
	private String info_RATEGANGE;
	private String info_RATEBUNYA;
	private String info_RATESOGE;
	private String info_RATECOMMON;
	private String info_RATEJUNMUN;
	private String info_RATEETC;
	private String info_YUNYOUNG;

	//ResultSet grcodenm 객체에서 필드 값을 받는 쿼리 필드 변수
	private String grcodenm_GRCODENM;

	//파라미터 변수 선언
	String p_grcode_Param;
	String p_year_Param;

	//ReportHandler 생성자 함수
	ReportHandler(HttpServletRequest request,HttpServletResponse response,Object[] userObj){
		this.request=request;
		this.response=response;
		this.userObj=userObj;
	}

	//ReportHandler 서비스 함수
	void service(JspWriter out) throws Exception{
		try{    //try 구문
			this.out=out;
			nMaxPage=0;    //nMaxPage 초기화

			//스크립트 헤더 함수 호출
			getScriptHeader("A4", "2100x2970", "9", "VERTICAL");

			//파라미터 설정 함수 호출
			setParam();

			//고정 데이터 초기화 함수 호출
			initConstVarient();

			//Connection 및 Statement 객체 생성 함수 호출
			createConnAndStateObject();

			//쿼리문 초기화 함수 호출
			initSQLConst();

			//쉬트 함수 호출
			//SHEET=Sheet1   FRAME=0 함수 호출
			executeSheet10();

			//---------------스크립트 종료---------------
			out.print("--SCRIPT_END--\r");
		}catch(Exception e){    //catch 구문
			out.print(e);
			out.print("AI!REPORT JSP ERROR!!!!\r");
		}finally{    //finally 구문
			try{    //finally try 구문
				//DataSet Close
				if(grcodenm!=null) grcodenm.close();
				if(stat_grcodenm!=null) stat_grcodenm.close();
				if(info!=null) info.close();
				if(stat_info!=null) stat_info.close();
				if(master!=null) master.close();
				if(stat_master!=null) stat_master.close();
				if(stat_detail!=null) stat_detail.close();
				if(totSum!=null) totSum.close();
				if(stat_totSum!=null) stat_totSum.close();
				if(conn_DUNET!=null) conn_DUNET.close();
			}catch(Exception e){    //finally catch 구문
			}    //end finally try
		}    //end try
	}

	//-----쉬트 함수-----
	//-----SHEET=Sheet1   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet10( ) throws Exception{
		//쉬트 초기화 함수 호출
		initSheetVariant(41, 41, 546, 801, true);

		//시작 페이지 번호 출력
		out.print("-- " + nPageNum + " PAGE --\r");

		//밴드 함수 호출
		getScriptFromtitle(true, true);    //Void 밴드 호출
		getScriptFrominfo_goal(true);    //반복 밴드 호출
		getScriptFrominfo_target(true);    //반복 밴드 호출
		getScriptFrominfo_inwon(true);    //반복 밴드 호출
		getScriptFrominfo_gigan(true);    //반복 밴드 호출
		getScriptFrominfo_yunyong(true);    //반복 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기

		//자식 쉬트 호출
		//SHEET=Sheet2   FRAME=0 함수 호출
		executeSheet20();
		//SHEET=Sheet3   FRAME=0 함수 호출
		executeSheet30();
	}

	//-----SHEET=Sheet2   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet20( ) throws Exception{
		//쉬트 초기화 함수 호출
		initChildSheetVariant(41, 41, 546, 801, false, false);

		//시작 페이지 번호 출력
		out.print("-- " + nPageNum + " PAGE --\r");

		//밴드 함수 호출
		getScriptFromv_edu(true, true);    //Void 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----SHEET=Sheet3   FRAME=Frame0 Start
	//-----폼 형식 : 상대 양식
	private void executeSheet30( ) throws Exception{
		//쉬트 초기화 함수 호출
		initChildSheetVariant(41, 41, 546, 801, false, false);

		//시작 페이지 번호 출력
		out.print("-- " + nPageNum + " PAGE --\r");

		//밴드 함수 호출
		getScriptFrommaster(true);    //반복 밴드 호출

		//페이지 및 좌표 설정
		nMaxPage=(int)MAX((long)nMaxPage, (long)nPageNum);    //생성된 최대 페이지 번호 구하기
	}

	//-----밴드 함수-----
	//----title VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet1    FRAME=Frame0
	//----밴드 이름 : title
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromtitle(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=76;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet grcodenm 객체의 생성
			if(grcodenm==null){
				grcodenm = stat_grcodenm.executeQuery(sql_grcodenm);
			}else{
				grcodenm.beforeFirst();
			}

			//데이터 fetch
			if(grcodenm.next()){
				setFieldVariableFromgrcodenm();	//ResultSet grcodenm에서 필드 값 설정
			}else{
				setFieldInitFromgrcodenm();	//ResultSet grcodenm의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet10_B2="";
			sheet10_E2="";

			//데이터 변수 할당
			sheet10_B2=grcodenm_GRCODENM;
			sheet10_E2=grcodenm_GRCODENM;
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScripttitle();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----info_goal RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : info_goal
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrominfo_goal(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A3_Buf="";
		sheet10_A3_Flag=true;
		sheet10_A3="";
		sheet10_C3="";
		bEnabledVirtualMerge_info_goal=false;

		//DataSet 객체 생성
		//ResultSet info 객체의 생성
		if(info==null){
			info = stat_info.executeQuery(sql_info);
		}else{
			info.beforeFirst();
		}

		while(info.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrominfo();	//RecordSet info에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			String sGoal = info_GOAL;

			info_GOAL =  "교 육 목 표";
			if(!sheet10_A3.equals(info_GOAL)){
				if(!bIsFirst){
					sheet10_A3_Buf=sheet10_A3;
					sheet10_A3_Flag=true;
				}
				sheet10_A3=info_GOAL;
			}
			info_GOAL = sGoal;
			sheet10_C3=info_GOAL;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergeinfo_goal();
			}

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergeinfo_goal();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptinfo_goal();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet10_A3_Flag){
					sheet10_A3_YPos=nYCurPos;
					sheet10_A3_Buf="";
					sheet10_A3_Flag=false;
				}
				bEnabledVirtualMerge_info_goal=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet10_A3_Buf=sheet10_A3;
		if(bIsPrint){
			writeScriptVirtualMergeinfo_goal();
		}
	}

	//----info_goal 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergeinfo_goal( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_info_goal){
			if(sheet10_A3_Buf.equals(isEmpty)){
				sheet10_A3_Buf=sheet10_A3;
			}else{
				sheet10_A3_Buf="";
			}
			sheet10_A3_Flag=true;
			writeScriptVirtualMergeinfo_goal();
		}
	}

	//-----info_target RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : info_target
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrominfo_target(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A4_Buf="";
		sheet10_A4_Flag=true;
		sheet10_A4="";
		sheet10_C4="";
		bEnabledVirtualMerge_info_target=false;

		//DataSet 객체 생성
		//ResultSet info 객체의 생성
		if(info==null){
			info = stat_info.executeQuery(sql_info);
		}else{
			info.beforeFirst();
		}

		while(info.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrominfo();	//RecordSet info에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			String sTarget = info_TARGET;

			info_TARGET =  "교 육 대 상";
			if(!sheet10_A4.equals(info_TARGET)){
				if(!bIsFirst){
					sheet10_A4_Buf=sheet10_A4;
					sheet10_A4_Flag=true;
				}
				sheet10_A4=info_TARGET;
			}
			info_TARGET = sTarget;
			sheet10_C4=info_TARGET;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergeinfo_target();
			}

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergeinfo_target();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptinfo_target();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet10_A4_Flag){
					sheet10_A4_YPos=nYCurPos;
					sheet10_A4_Buf="";
					sheet10_A4_Flag=false;
				}
				bEnabledVirtualMerge_info_target=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet10_A4_Buf=sheet10_A4;
		if(bIsPrint){
			writeScriptVirtualMergeinfo_target();
		}
	}

	//----info_target 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergeinfo_target( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_info_target){
			if(sheet10_A4_Buf.equals(isEmpty)){
				sheet10_A4_Buf=sheet10_A4;
			}else{
				sheet10_A4_Buf="";
			}
			sheet10_A4_Flag=true;
			writeScriptVirtualMergeinfo_target();
		}
	}

	//-----info_inwon RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : info_inwon
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrominfo_inwon(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A5_Buf="";
		sheet10_A5_Flag=true;
		sheet10_A5="";
		sheet10_C5="";
		bEnabledVirtualMerge_info_inwon=false;

		//DataSet 객체 생성
		//ResultSet info 객체의 생성
		if(info==null){
			info = stat_info.executeQuery(sql_info);
		}else{
			info.beforeFirst();
		}

		while(info.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrominfo();	//RecordSet info에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			String sInwon = info_INWON;

			info_INWON =  "교 육 인 원";
			if(!sheet10_A5.equals(info_INWON)){
				if(!bIsFirst){
					sheet10_A5_Buf=sheet10_A5;
					sheet10_A5_Flag=true;
				}
				sheet10_A5=info_INWON;
			}
			info_INWON = sInwon;
			sheet10_C5=info_INWON;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergeinfo_inwon();
			}

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergeinfo_inwon();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptinfo_inwon();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet10_A5_Flag){
					sheet10_A5_YPos=nYCurPos;
					sheet10_A5_Buf="";
					sheet10_A5_Flag=false;
				}
				bEnabledVirtualMerge_info_inwon=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet10_A5_Buf=sheet10_A5;
		if(bIsPrint){
			writeScriptVirtualMergeinfo_inwon();
		}
	}

	//----info_inwon 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergeinfo_inwon( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_info_inwon){
			if(sheet10_A5_Buf.equals(isEmpty)){
				sheet10_A5_Buf=sheet10_A5;
			}else{
				sheet10_A5_Buf="";
			}
			sheet10_A5_Flag=true;
			writeScriptVirtualMergeinfo_inwon();
		}
	}

	//-----info_gigan RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : info_gigan
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrominfo_gigan(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A6_Buf="";
		sheet10_A6_Flag=true;
		sheet10_A6="";
		sheet10_C6="";
		bEnabledVirtualMerge_info_gigan=false;

		//DataSet 객체 생성
		//ResultSet info 객체의 생성
		if(info==null){
			info = stat_info.executeQuery(sql_info);
		}else{
			info.beforeFirst();
		}

		while(info.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrominfo();	//RecordSet info에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			String sGigan = info_GIGAN;

			info_GIGAN=  "교 육 일 정";
			if(!sheet10_A6.equals(info_GIGAN)){
				if(!bIsFirst){
					sheet10_A6_Buf=sheet10_A6;
					sheet10_A6_Flag=true;
				}
				sheet10_A6=info_GIGAN;
			}
			info_GIGAN = sGigan;
			sheet10_C6=info_GIGAN;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergeinfo_gigan();
			}

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergeinfo_gigan();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptinfo_gigan();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet10_A6_Flag){
					sheet10_A6_YPos=nYCurPos;
					sheet10_A6_Buf="";
					sheet10_A6_Flag=false;
				}
				bEnabledVirtualMerge_info_gigan=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet10_A6_Buf=sheet10_A6;
		if(bIsPrint){
			writeScriptVirtualMergeinfo_gigan();
		}
	}

	//----info_gigan 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergeinfo_gigan( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_info_gigan){
			if(sheet10_A6_Buf.equals(isEmpty)){
				sheet10_A6_Buf=sheet10_A6;
			}else{
				sheet10_A6_Buf="";
			}
			sheet10_A6_Flag=true;
			writeScriptVirtualMergeinfo_gigan();
		}
	}

	//-----info_yunyong RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet1   FRAME=Frame0
	//-----밴드 이름 : info_yunyong
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrominfo_yunyong(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet10_A7_Buf="";
		sheet10_A7_Flag=true;
		sheet10_A7="";
		sheet10_C7="";
		bEnabledVirtualMerge_info_yunyong=false;

		//DataSet 객체 생성
		//ResultSet info 객체의 생성
		if(info==null){
			info = stat_info.executeQuery(sql_info);
		}else{
			info.beforeFirst();
		}

		while(info.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrominfo();	//RecordSet info에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			String sYunyoung = info_YUNYOUNG;

			info_YUNYOUNG=  "교 육 운 영";
			if(!sheet10_A7.equals(info_YUNYOUNG)){
				if(!bIsFirst){
					sheet10_A7_Buf=sheet10_A7;
					sheet10_A7_Flag=true;
				}
				sheet10_A7=info_YUNYOUNG;
			}
			info_YUNYOUNG =sYunyoung ;
			sheet10_C7=info_YUNYOUNG;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergeinfo_yunyong();
			}

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergeinfo_yunyong();

					//페이지 스킵 함수 호출
					pageSkip(10);
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptinfo_yunyong();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet10_A7_Flag){
					sheet10_A7_YPos=nYCurPos;
					sheet10_A7_Buf="";
					sheet10_A7_Flag=false;
				}
				bEnabledVirtualMerge_info_yunyong=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet10_A7_Buf=sheet10_A7;
		if(bIsPrint){
			writeScriptVirtualMergeinfo_yunyong();
		}
	}

	//----info_yunyong 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergeinfo_yunyong( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_info_yunyong){
			if(sheet10_A7_Buf.equals(isEmpty)){
				sheet10_A7_Buf=sheet10_A7;
			}else{
				sheet10_A7_Buf="";
			}
			sheet10_A7_Flag=true;
			writeScriptVirtualMergeinfo_yunyong();
		}
	}

	//----v_edu VoidBand Start----
	//----소속 쉬트 : SHEET=Sheet2    FRAME=Frame0
	//----밴드 이름 : v_edu
	//----밴드 종류 : Void 밴드
	//----bIsFrist : 부모 밴드 함수나 쉬트 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	//----nRepeatCnt : 부모 반복 밴드 수행 횟수와 연동 옵션 설정시 void 밴드가 수행할 반복 횟수 전달
	private void getScriptFromv_edu(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=121;    //밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet info 객체의 생성
			if(info==null){
				info = stat_info.executeQuery(sql_info);
			}else{
				info.beforeFirst();
			}

			//데이터 fetch
			if(info.next()){
				setFieldVariableFrominfo();	//ResultSet info에서 필드 값 설정
			}else{
				setFieldInitFrominfo();	//ResultSet info의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet20_D4="";
			sheet20_E4="";
			sheet20_F4="";
			sheet20_G4="";
			sheet20_H4="";
			sheet20_I4="";
			sheet20_D5="";
			sheet20_E5="";
			sheet20_F5="";
			sheet20_G5="";
			sheet20_H5="";
			sheet20_I5="";

			//데이터 변수 할당
			sheet20_D4=info_SIGANGE;
			sheet20_E4=info_SIBUNYA;
			sheet20_F4=info_SISOGE;
			sheet20_G4=info_SICOMMON;
			sheet20_H4=info_SIJUNMUN;
			sheet20_I4=info_SIETC;
			sheet20_D5=info_RATEGANGE;
			sheet20_E5=info_RATEBUNYA;
			sheet20_F5=info_RATESOGE;
			sheet20_G5=info_RATECOMMON;
			sheet20_H5=info_RATEJUNMUN;
			sheet20_I5=info_RATEETC;
		}    //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptv_edu();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//----header RepeatHeader Start----
	//----소속 쉬트 : SHEET=Sheet3    FRAME=Frame0
	//----밴드 이름 : header
	//----밴드 종류 : 반복 헤더
	//----bIsFrist : 반복 밴드 함수에서 최초로 호출될 때 true, 그 이후 호출될 때 false
	//----bIsPrint : 감추기 속성 설정 여부. treu면 출력, false면 AI 스크립트를 생성하지 않음.
	private void getScriptFromheader(boolean bIsFirst, boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=60;	//밴드 출력 높이

		if(bIsFirst){   //밴드 최초 호출 시에만 실행되는 코드
			//DataSet 객체 생성
			//ResultSet totSum 객체의 생성
			if(totSum==null){
				totSum = stat_totSum.executeQuery(sql_totSum);
			}else{
				totSum.beforeFirst();
			}

			//데이터 fetch
			if(totSum.next()){
				setFieldVariableFromtotSum();	//ResultSet totSum에서 필드 값 설정
			}else{
				setFieldInitFromtotSum();	//ResultSet totSum의 필드 값 초기화
			}

			//데이터 변수 초기화
			sheet30_C3=0;
			sheet30_D3=0;
			sheet30_E3=0;

			//데이터 변수 할당
			sheet30_C3=totSum_TOT_TITLE1_SUB1;
			sheet30_D3=totSum_TOT_TITLE1_SUB2;
			sheet30_E3=totSum_TOT_TITLE1_SUB3;
		}   //end if(bIsFirst)

		//AI 스크립트 출력
		if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
			//스크립트 출력 영역 검사
			if(isPageSkip(nYCurPos+nBandHeight)){
				pageSkip(10);
			}

			//스크립트 출력 함수 호출
			writeScriptheader();

			//다음 출력 좌표 설정
			nYCurPos=nYCurPos+nBandHeight;
		}   //end if(bIsPrint)
	}

	//-----detail RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet3   FRAME=Frame0
	//-----밴드 이름 : detail
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFromdetail(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;
		//폰트명 : 돋움체
		//폰트 사이즈 : 10
		//각 문자별 폭을 할당할 배열 선언
		int[] charWidth = {5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,10};

		//데이터 변수 초기화
		sheet30_A5_Buf="";
		sheet30_A5_Flag=true;
		sheet30_A5="";
		sheet30_B5="";
		sheet30_C5=0;
		sheet30_D5=0;
		sheet30_E5=0;
		sheet30_F5="";
		bEnabledVirtualMerge_detail=false;

		//DataSet 객체 생성
		//ResultSet detail 객체의 생성
		initSQLdetailVarient();
		detail = stat_detail.executeQuery(sql_detail);

		while(detail.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFromdetail();	//RecordSet detail에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
			}   //end if(bIsFirst)

			//데이터 변수 할당
			if(!sheet30_A5.equals(detail_GUBUN)){
				if(!bIsFirst){
					sheet30_A5_Buf=sheet30_A5;
					sheet30_A5_Flag=true;
				}
				sheet30_A5=detail_GUBUN;
			}
			sheet30_B5=detail_ANNAE_TITLE;
			sheet30_C5=detail_TITLE1_SUB1;
			sheet30_D5=detail_TITLE1_SUB2;
			sheet30_E5=detail_TITLE1_SUB3;
			sheet30_F5=detail_TITLE1_SUB4;

			//루프 내부 가상병합 출력 함수 호출
			if(bIsPrint){
				writeScriptVirtualMergedetail();
			}

			//Auto Size Code
			nAutoHeight_detail[0]=0;
			nAutoHeight_detail[0]=getPrintHeight(sheet30_F5, charWidth, 10, 82, 20, nAutoHeight_detail[0]);
			nAutoHeight_detail[0]=nAutoHeight_detail[0]+20;
			nBandHeight=nAutoHeight_detail[0];   //밴드 출력 높이 설정

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//가상병합 출력 및 한번만 데이터 Reset
					pageSkipVirtualMergedetail();

					//페이지 스킵 함수 호출
					pageSkip(10);

					//반복 헤더 및 부모 반복단위 호출
					getScriptFromheader(false, true);	//반복 헤더 호출
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptdetail();

				//페이지 연결 출력 및 가상병합 플래그 Reset
				if(sheet30_A5_Flag){
					sheet30_A5_YPos=nYCurPos;
					sheet30_A5_Buf="";
					sheet30_A5_Flag=false;
				}
				bEnabledVirtualMerge_detail=true;

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end

		//루프 외부 가상병합 출력 함수 호출
		sheet30_A5_Buf=sheet30_A5;
		if(bIsPrint){
			writeScriptVirtualMergedetail();
		}

		//DataSet Close
		if(detail!=null) detail.close();
	}

	//----detail 반복밴드 Page Skip시 가상 병합 데이터 설정 및 출력 함수----
	private void pageSkipVirtualMergedetail( ) throws Exception{
		//가상 병합 데이터 설정 및 출력
		if(bEnabledVirtualMerge_detail){
			if(sheet30_A5_Buf.equals(isEmpty)){
				sheet30_A5_Buf=sheet30_A5;
			}else{
				sheet30_A5_Buf="";
			}
			sheet30_A5_Flag=true;
			writeScriptVirtualMergedetail();
		}
	}

	//-----master RepeatBand Start-----
	//-----소속 쉬트 : SHEET=Sheet3   FRAME=Frame0
	//-----밴드 이름 : master
	//-----밴드 종류 : 반복 밴드
	//-----bIsPrint : 감추기 속성 설정 여부 true면 출력, false면 스크립트를 생성하지 않음
	private void getScriptFrommaster(boolean bIsPrint) throws Exception{
		//지역 변수 선언 및 초기화
		int nBandHeight=20;    //밴드 출력 높이
		boolean bIsFirst=true;

		//데이터 변수 초기화
		sheet30_C4=0;
		sheet30_D4=0;
		sheet30_E4=0;

		//DataSet 객체 생성
		//ResultSet master 객체의 생성
		if(master==null){
			master = stat_master.executeQuery(sql_master);
		}else{
			master.beforeFirst();
		}

		while(master.next()){   //자동으로 생성되는 반복 밴드의 루프문
			//데이터 fetch
			setFieldVariableFrommaster();	//RecordSet master에서 필드 값 설정

			if(bIsFirst){   //밴드 호출 후 루프 내에서 한번 만 실행되는 코드
				//반복 헤더 호출 및 조건 플래그 초기화
				getScriptFromheader(bIsFirst, true);	//반복 헤더 호출
			}   //end if(bIsFirst)

			//데이터 변수 할당
			sheet30_C4=master_TOT_TITLE1_SUB1;
			sheet30_D4=master_TOT_TITLE1_SUB2;
			sheet30_E4=master_TOT_TITLE1_SUB3;

			//AI 스크립트 출력
			if(bIsPrint){   //감추기 속성이 지정되지 않으면 bIsPrint는 true
				if(isPageSkip(nYCurPos+nBandHeight)){   //스크립트 출력 영역 검사
					//페이지 스킵 함수 호출
					pageSkip(10);

					//반복 헤더 및 부모 반복단위 호출
					getScriptFromheader(false, true);	//반복 헤더 호출
				}   //end if(page skip test)

				//스크립트 출력 함수 호출
				writeScriptmaster();

				//다음 출력 좌표 설정
				nYCurPos=nYCurPos+nBandHeight;
			}   //end if(bIsPrint)

			//루프 내부 자식 밴드 호출
			getScriptFromdetail(true);

			//bIsFirst 및 출력 라인 설정
			bIsFirst=false;
		}   //while end
	}

	//-----스크립트 출력 함수-----
	//----title 스크립트 문 출력 함수----
	private void writeScripttitle( ) throws Exception{
		//스크립트문 생성
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos)+",504,1,14,0/,굴림체,RGB[0,0,0],BOLD, , ,NONE,56,1)");
		out.println(sheet10_A1+"\r");
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos+56)+",126,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos+56)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_A2+"\r");
		out.println("^CELLBG("+(nXCurPos+126)+","+(nYCurPos+56)+",126,20,1,RGB[255,255,255],RGB[255,255,255],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos+56)+",126,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_B2+"\r");
		out.println("^CELLBG("+(nXCurPos+252)+","+(nYCurPos+56)+",126,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+252)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+252)+","+(nYCurPos+56)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_D2+"\r");
		out.println("^CELLLINE("+(nXCurPos+378)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+378)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+378)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+378)+","+(nYCurPos+56)+",126,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+378)+","+(nYCurPos+56)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_E2+"\r");
	}

	//----info_goal 스크립트 문 출력 함수----
	private void writeScriptinfo_goal( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],2)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos)+",20,2,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_B3+"\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+146)+","+(nYCurPos)+",358,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C3+"\r");
	}

	//----info_goal VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergeinfo_goal( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet10_A3_Buf.equals(isEmpty)){
			out.println("^CELLBG("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,"+(nYCurPos-sheet10_A3_YPos)+",1,RGB[230,230,250],RGB[230,230,250],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,"+(nYCurPos-sheet10_A3_YPos)+",0,RGB[0,0,0],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,"+(nYCurPos-sheet10_A3_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,"+(nYCurPos-sheet10_A3_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,"+(nYCurPos-sheet10_A3_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet10_A3_YPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet10_A3_YPos)+",1)");
			out.println(sheet10_A3_Buf+"\r");
		}
	}

	//----info_target 스크립트 문 출력 함수----
	private void writeScriptinfo_target( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],2)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos)+",20,2,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_B4+"\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+146)+","+(nYCurPos)+",358,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C4+"\r");
	}

	//----info_target VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergeinfo_target( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet10_A4_Buf.equals(isEmpty)){
			out.println("^CELLBG("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,"+(nYCurPos-sheet10_A4_YPos)+",1,RGB[230,230,250],RGB[230,230,250],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,"+(nYCurPos-sheet10_A4_YPos)+",0,RGB[0,0,0],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,"+(nYCurPos-sheet10_A4_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,"+(nYCurPos-sheet10_A4_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,"+(nYCurPos-sheet10_A4_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet10_A4_YPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet10_A4_YPos)+",1)");
			out.println(sheet10_A4_Buf+"\r");
		}
	}

	//----info_inwon 스크립트 문 출력 함수----
	private void writeScriptinfo_inwon( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],2)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos)+",20,2,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_B5+"\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+146)+","+(nYCurPos)+",358,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C5+"\r");
	}

	//----info_inwon VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergeinfo_inwon( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet10_A5_Buf.equals(isEmpty)){
			out.println("^CELLBG("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,"+(nYCurPos-sheet10_A5_YPos)+",1,RGB[230,230,250],RGB[230,230,250],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,"+(nYCurPos-sheet10_A5_YPos)+",0,RGB[0,0,0],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,"+(nYCurPos-sheet10_A5_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,"+(nYCurPos-sheet10_A5_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,"+(nYCurPos-sheet10_A5_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet10_A5_YPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet10_A5_YPos)+",1)");
			out.println(sheet10_A5_Buf+"\r");
		}
	}

	//----info_gigan 스크립트 문 출력 함수----
	private void writeScriptinfo_gigan( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],2)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos)+",20,2,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_B6+"\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+146)+","+(nYCurPos)+",358,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C6+"\r");
	}

	//----info_gigan VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergeinfo_gigan( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet10_A6_Buf.equals(isEmpty)){
			out.println("^CELLBG("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,"+(nYCurPos-sheet10_A6_YPos)+",1,RGB[230,230,250],RGB[230,230,250],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,"+(nYCurPos-sheet10_A6_YPos)+",0,RGB[0,0,0],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,"+(nYCurPos-sheet10_A6_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,"+(nYCurPos-sheet10_A6_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,"+(nYCurPos-sheet10_A6_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet10_A6_YPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet10_A6_YPos)+",1)");
			out.println(sheet10_A6_Buf+"\r");
		}
	}

	//----info_yunyong 스크립트 문 출력 함수----
	private void writeScriptinfo_yunyong( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",20,20,0,RGB[0,0,0],2)\r");
		out.print("^PRINT("+(nXCurPos+126)+","+(nYCurPos)+",20,2,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,2)");
		out.println(sheet10_B7+"\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+146)+","+(nYCurPos)+",358,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+146)+","+(nYCurPos)+",358,0,11,0/,굴림체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet10_C7+"\r");
	}

	//----info_yunyong VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergeinfo_yunyong( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet10_A7_Buf.equals(isEmpty)){
			out.println("^CELLBG("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,"+(nYCurPos-sheet10_A7_YPos)+",1,RGB[230,230,250],RGB[230,230,250],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,"+(nYCurPos-sheet10_A7_YPos)+",0,RGB[0,0,0],0)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,"+(nYCurPos-sheet10_A7_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,"+(nYCurPos-sheet10_A7_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,"+(nYCurPos-sheet10_A7_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet10_A7_YPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet10_A7_YPos)+",1)");
			out.println(sheet10_A7_Buf+"\r");
		}
	}

	//----v_edu 스크립트 문 출력 함수----
	private void writeScriptv_edu( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos)+",126,101,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",126,101,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",126,101,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",126,101,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",126,101,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos)+",126,1,11,0/,굴림체,RGB[0,0,0], , , ,NONE,101,1)");
		out.println(sheet20_A1+"\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos)+",8,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos)+",34,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos)+",43,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos)+",40,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos)+",59,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos)+",59,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos)+",59,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos)+",68,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos)+",8,11,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos)+",8,11,0,RGB[0,0,0],3)\r");
		out.println("^CELLBG("+(nXCurPos+134)+","+(nYCurPos+11)+",34,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+11)+",34,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+11)+",34,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+11)+",34,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+11)+",34,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+134)+","+(nYCurPos+11)+",34,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet20_C2+"\r");
		out.println("^CELLBG("+(nXCurPos+168)+","+(nYCurPos+11)+",43,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+11)+",43,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+11)+",43,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+11)+",43,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+11)+",43,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+168)+","+(nYCurPos+11)+",43,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet20_D2+"\r");
		out.println("^CELLBG("+(nXCurPos+211)+","+(nYCurPos+11)+",40,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+11)+",40,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+11)+",40,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+11)+",40,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+11)+",40,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+211)+","+(nYCurPos+11)+",40,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet20_E2+"\r");
		out.println("^CELLBG("+(nXCurPos+251)+","+(nYCurPos+11)+",177,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+11)+",177,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+11)+",177,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+11)+",177,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+11)+",177,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+251)+","+(nYCurPos+11)+",177,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_F2+"\r");
		out.println("^CELLBG("+(nXCurPos+428)+","+(nYCurPos+11)+",68,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+11)+",68,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+11)+",68,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+11)+",68,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+11)+",68,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+428)+","+(nYCurPos+11)+",68,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet20_I2+"\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+11)+",8,20,0,RGB[0,0,0],3)\r");
		out.println("^CELLBG("+(nXCurPos+251)+","+(nYCurPos+31)+",59,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+251)+","+(nYCurPos+31)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_F3+"\r");
		out.println("^CELLBG("+(nXCurPos+310)+","+(nYCurPos+31)+",59,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+310)+","+(nYCurPos+31)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_G3+"\r");
		out.println("^CELLBG("+(nXCurPos+369)+","+(nYCurPos+31)+",59,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+31)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+369)+","+(nYCurPos+31)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_H3+"\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+31)+",8,20,0,RGB[0,0,0],3)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+51)+",34,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+51)+",34,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+51)+",34,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+51)+",34,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+134)+","+(nYCurPos+51)+",34,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_C4+"\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+51)+",43,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+51)+",43,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+51)+",43,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+51)+",43,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+168)+","+(nYCurPos+51)+",43,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_D4+"\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+51)+",40,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+51)+",40,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+51)+",40,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+51)+",40,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+211)+","+(nYCurPos+51)+",40,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_E4+"\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+251)+","+(nYCurPos+51)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_F4+"\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+310)+","+(nYCurPos+51)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_G4+"\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+51)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+369)+","+(nYCurPos+51)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_H4+"\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+51)+",68,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+51)+",68,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+51)+",68,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+51)+",68,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+428)+","+(nYCurPos+51)+",68,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_I4+"\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+51)+",8,20,0,RGB[0,0,0],3)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+71)+",34,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+71)+",34,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+71)+",34,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+71)+",34,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+134)+","+(nYCurPos+71)+",34,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_C5+"\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+71)+",43,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+71)+",43,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+71)+",43,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+71)+",43,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+168)+","+(nYCurPos+71)+",43,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_D5+"\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+71)+",40,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+71)+",40,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+71)+",40,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+71)+",40,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+211)+","+(nYCurPos+71)+",40,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_E5+"\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+251)+","+(nYCurPos+71)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_F5+"\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+310)+","+(nYCurPos+71)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_G5+"\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+71)+",59,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+369)+","+(nYCurPos+71)+",59,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_H5+"\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+71)+",68,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+71)+",68,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+71)+",68,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+71)+",68,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+428)+","+(nYCurPos+71)+",68,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet20_I5+"\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+71)+",8,20,0,RGB[0,0,0],3)\r");
		out.println("^CELLLINE("+(nXCurPos+126)+","+(nYCurPos+91)+",8,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+134)+","+(nYCurPos+91)+",34,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+168)+","+(nYCurPos+91)+",43,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+211)+","+(nYCurPos+91)+",40,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+251)+","+(nYCurPos+91)+",59,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+310)+","+(nYCurPos+91)+",59,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+369)+","+(nYCurPos+91)+",59,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+428)+","+(nYCurPos+91)+",68,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+91)+",8,10,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+496)+","+(nYCurPos+91)+",8,10,0,RGB[0,0,0],3)\r");
	}

	//----header 스크립트 문 출력 함수----
	private void writeScriptheader( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos)+",112,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos)+",112,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet30_A1+"\r");
		out.println("^CELLBG("+(nXCurPos+112)+","+(nYCurPos)+",112,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+112)+","+(nYCurPos)+",112,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet30_B1+"\r");
		out.println("^CELLBG("+(nXCurPos+224)+","+(nYCurPos)+",198,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",198,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",198,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",198,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",198,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+224)+","+(nYCurPos)+",198,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_C1+"\r");
		out.println("^CELLBG("+(nXCurPos+422)+","+(nYCurPos)+",82,40,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,40,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,40,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,40,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,40,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+422)+","+(nYCurPos)+",82,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,40,1)");
		out.println(sheet30_F1+"\r");
		out.println("^CELLBG("+(nXCurPos+224)+","+(nYCurPos+20)+",66,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+224)+","+(nYCurPos+20)+",66,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_C2+"\r");
		out.println("^CELLBG("+(nXCurPos+290)+","+(nYCurPos+20)+",66,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+290)+","+(nYCurPos+20)+",66,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_D2+"\r");
		out.println("^CELLBG("+(nXCurPos+356)+","+(nYCurPos+20)+",66,20,1,RGB[230,230,250],RGB[230,230,250],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+20)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+356)+","+(nYCurPos+20)+",66,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_E2+"\r");
		out.println("^CELLBG("+(nXCurPos)+","+(nYCurPos+40)+",224,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+40)+",224,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+40)+",224,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+40)+",224,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos+40)+",224,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos)+","+(nYCurPos+40)+",224,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_A3+"\r");
		out.println("^CELLBG("+(nXCurPos+224)+","+(nYCurPos+40)+",66,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+224)+","+(nYCurPos+40)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_C3+"\r");
		out.println("^CELLBG("+(nXCurPos+290)+","+(nYCurPos+40)+",66,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+290)+","+(nYCurPos+40)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_D3+"\r");
		out.println("^CELLBG("+(nXCurPos+356)+","+(nYCurPos+40)+",66,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos+40)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+356)+","+(nYCurPos+40)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_E3+"\r");
		out.println("^CELLBG("+(nXCurPos+422)+","+(nYCurPos+40)+",82,20,1,RGB[192,192,192],RGB[192,192,192],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos+40)+",82,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos+40)+",82,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos+40)+",82,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos+40)+",82,20,0,RGB[0,0,0],3)\r");
	}

	//----detail 스크립트 문 출력 함수----
	private void writeScriptdetail( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+112)+","+(nYCurPos)+",112,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,"+(nAutoHeight_detail[0])+",1)");
		out.println(sheet30_B5+"\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+224)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,"+(nAutoHeight_detail[0])+",1)");
		out.println(sheet30_C5+"\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+290)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,XL,"+(nAutoHeight_detail[0])+",1)");
		out.println(sheet30_D5+"\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+356)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,XL,"+(nAutoHeight_detail[0])+",1)");
		out.println(sheet30_E5+"\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,"+(nAutoHeight_detail[0])+",0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+422)+","+(nYCurPos)+",82,0,10,0/,돋움체,RGB[0,0,0], , , ,XL,"+(nAutoHeight_detail[0])+",1)");
		out.println(sheet30_F5+"\r");
	}

	//----detail VirtualMerge 스크립트 문 출력 함수----
	private void writeScriptVirtualMergedetail( ) throws Exception{
		//가상병합 스크립트문 생성
		if(!sheet30_A5_Buf.equals(isEmpty)){
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet30_A5_YPos)+",112,"+(nYCurPos-sheet30_A5_YPos)+",0,RGB[0,0,0],1)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet30_A5_YPos)+",112,"+(nYCurPos-sheet30_A5_YPos)+",0,RGB[0,0,0],2)\r");
			out.println("^CELLLINE("+(nXCurPos)+","+(sheet30_A5_YPos)+",112,"+(nYCurPos-sheet30_A5_YPos)+",0,RGB[0,0,0],3)\r");
			out.print("^PRINT("+(nXCurPos)+","+(sheet30_A5_YPos)+",112,1,10,0/,돋움체,RGB[0,0,0], , , ,NONE,"+(nYCurPos-sheet30_A5_YPos)+",0)");
			out.println(sheet30_A5_Buf+"\r");
		}
	}

	//----master 스크립트 문 출력 함수----
	private void writeScriptmaster( ) throws Exception{
		//스크립트문 생성
		out.println("^CELLLINE("+(nXCurPos)+","+(nYCurPos)+",112,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+112)+","+(nYCurPos)+",112,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+112)+","+(nYCurPos)+",112,1,10,0/,돋움체,RGB[0,0,0],BOLD, , ,NONE,20,1)");
		out.println(sheet30_B4+"\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+224)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+224)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_C4+"\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+290)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+290)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_D4+"\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+356)+","+(nYCurPos)+",66,20,0,RGB[0,0,0],3)\r");
		out.print("^PRINT("+(nXCurPos+356)+","+(nYCurPos)+",66,1,10,1/1/0,돋움체,RGB[0,0,0], , , ,NONE,20,1)");
		out.println(sheet30_E4+"\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,20,0,RGB[0,0,0],0)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,20,0,RGB[0,0,0],1)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,20,0,RGB[0,0,0],2)\r");
		out.println("^CELLLINE("+(nXCurPos+422)+","+(nYCurPos)+",82,20,0,RGB[0,0,0],3)\r");
	}

	//파라미터 설정 함수
	private void setParam(){
		p_grcode_Param=toKor(GetB(request.getParameter("p_grcode")));
		p_year_Param=toKor(GetB(request.getParameter("p_year")));
	}

	//-----Connection 및 Statement 객체 생성 함수-----
	private void createConnAndStateObject() throws Exception{
		//DUNET Connection 객체 생성
		Class.forName("oracle.jdbc.driver.OracleDriver");
		conn_DUNET = DriverManager.getConnection("jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.12.203)(PORT=1521))(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.12.204)(PORT=1521))(FAILOVER=on)(LOAD_BALANCE=off))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=LOTI)))","inchlms","fhxl21");stat_totSum=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		stat_detail=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		stat_master=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		stat_info=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
		stat_grcodenm=conn_DUNET.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
	}

	//-----SQL문 변수 초기화 함수-----
	private void initSQLConst(){
		sql_totSum = "SELECT SUM(TITLE1_SUB1) AS TOT_TITLE1_SUB1 ";
		sql_totSum = sql_totSum + "     , SUM(TITLE1_SUB2) AS TOT_TITLE1_SUB2 ";
		sql_totSum = sql_totSum + "     , SUM(TITLE1_SUB3) AS TOT_TITLE1_SUB3 ";
		sql_totSum = sql_totSum + "  FROM ( ";
		sql_totSum = sql_totSum + "SELECT GRCODE ";
		sql_totSum = sql_totSum + "     , YEAR ";
		sql_totSum = sql_totSum + "     , DECODE(ANNAE_GUBUN,1,'소양분야',2,'직무분야',3,'행정기타') AS GUBUN ";
		sql_totSum = sql_totSum + "     , ANNAE_SEQ ";
		sql_totSum = sql_totSum + "     , ANNAE_TITLE ";
		sql_totSum = sql_totSum + "     , TITLE1_SUB1 ";
		sql_totSum = sql_totSum + "     , TITLE1_SUB2 ";
		sql_totSum = sql_totSum + "     , TITLE1_SUB3 ";
		sql_totSum = sql_totSum + "     , TITLE1_SUB4 ";
		sql_totSum = sql_totSum + "     , GRCODE, YEAR ";
		sql_totSum = sql_totSum + "  FROM TB_GRANNAE2 ";
		sql_totSum = sql_totSum + " WHERE YEAR = '" + p_year_Param + "' ";
		sql_totSum = sql_totSum + " AND GRCODE = '" + p_grcode_Param + "' ";
		sql_totSum = sql_totSum + "ORDER BY ANNAE_GUBUN, ANNAE_SEQ )";
		sql_master = "SELECT ANNAE_GUBUN ";
		sql_master = sql_master + "     , SUM(TITLE1_SUB1) AS TOT_TITLE1_SUB1 ";
		sql_master = sql_master + "     , SUM(TITLE1_SUB2) AS TOT_TITLE1_SUB2 ";
		sql_master = sql_master + "     , SUM(TITLE1_SUB3) AS TOT_TITLE1_SUB3 ";
		sql_master = sql_master + "     , DECODE(ANNAE_GUBUN,1,'소양분야',2,'직무분야',3,'행정기타') AS GUBUN ";
		sql_master = sql_master + "  FROM ( ";
		sql_master = sql_master + "SELECT GRCODE ";
		sql_master = sql_master + "     , YEAR ";
		sql_master = sql_master + "     , DECODE(ANNAE_GUBUN,1,'소양분야',2,'직무분야',3,'행정기타') AS GUBUN ";
		sql_master = sql_master + "     , ANNAE_SEQ ";
		sql_master = sql_master + "     , ANNAE_TITLE ";
		sql_master = sql_master + "     , TITLE1_SUB1 ";
		sql_master = sql_master + "     , TITLE1_SUB2 ";
		sql_master = sql_master + "     , TITLE1_SUB3 ";
		sql_master = sql_master + "     , TITLE1_SUB4 ";
		sql_master = sql_master + "     , ANNAE_GUBUN ";
		sql_master = sql_master + "  FROM TB_GRANNAE2 ";
		sql_master = sql_master + " WHERE YEAR = '" + p_year_Param + "' ";
		sql_master = sql_master + " AND GRCODE = '" + p_grcode_Param + "' ";
		sql_master = sql_master + "ORDER BY ANNAE_GUBUN, ANNAE_SEQ )  ";
		sql_master = sql_master + "GROUP BY ANNAE_GUBUN";
		sql_info = "SELECT GRCODE, YEAR, GOAL, TARGET, INWON, GIGAN, SIGANGE, SIBUNYA, SISOGE, SICOMMON, SIJUNMUN, SIETC, RATEGANGE, RATEBUNYA, RATESOGE, RATECOMMON, RATEJUNMUN, RATEETC, YUNYOUNG  ";
		sql_info = sql_info + "FROM TB_GRANNAE WHERE GRCODE = '" + p_grcode_Param + "' AND YEAR = '" + p_year_Param + "'";
		sql_grcodenm = "select distinct grcodenm from tb_grcode where grcode = '" + p_grcode_Param + "'";
	}

	private void initSQLdetailVarient(){
		sql_detail = "SELECT GRCODE ";
		sql_detail = sql_detail + "     , YEAR ";
		sql_detail = sql_detail + "     , DECODE(ANNAE_GUBUN,1,'소양분야',2,'직무분야',3,'행정기타') AS GUBUN ";
		sql_detail = sql_detail + "     , ANNAE_SEQ ";
		sql_detail = sql_detail + "     , ANNAE_TITLE ";
		sql_detail = sql_detail + "     , TITLE1_SUB1 ";
		sql_detail = sql_detail + "     , TITLE1_SUB2 ";
		sql_detail = sql_detail + "     , TITLE1_SUB3 ";
		sql_detail = sql_detail + "     , TITLE1_SUB4 ";
		sql_detail = sql_detail + "  FROM TB_GRANNAE2 ";
		sql_detail = sql_detail + " WHERE YEAR = '" + p_year_Param + "' ";
		sql_detail = sql_detail + " AND GRCODE = '" + p_grcode_Param + "' ";
		sql_detail = sql_detail + " AND ANNAE_GUBUN = '" + master_ANNAE_GUBUN + "' ";
		sql_detail = sql_detail + "ORDER BY ANNAE_GUBUN, ANNAE_SEQ";
	}

	//-----ResultSet 객체에서 필드 값 설정 함수-----
	//ResultSet totSum 객체에서 필드 값 설정 함수
	private void setFieldVariableFromtotSum() throws Exception{
		totSum_TOT_TITLE1_SUB1=totSum.getDouble(1);
		totSum_TOT_TITLE1_SUB2=totSum.getDouble(2);
		totSum_TOT_TITLE1_SUB3=totSum.getDouble(3);
	}

	//ResultSet totSum 객체의 필드 값 초기화 함수
	private void setFieldInitFromtotSum(){
		totSum_TOT_TITLE1_SUB1=0;
		totSum_TOT_TITLE1_SUB2=0;
		totSum_TOT_TITLE1_SUB3=0;
	}

	//ResultSet detail 객체에서 필드 값 설정 함수
	private void setFieldVariableFromdetail() throws Exception{
		detail_GRCODE=GetB(detail.getString(1));
		detail_YEAR=GetB(detail.getString(2));
		detail_GUBUN=GetB(detail.getString(3));
		detail_ANNAE_SEQ=detail.getDouble(4);
		detail_ANNAE_TITLE=GetB(detail.getString(5));
		detail_TITLE1_SUB1=detail.getDouble(6);
		detail_TITLE1_SUB2=detail.getDouble(7);
		detail_TITLE1_SUB3=detail.getDouble(8);
		detail_TITLE1_SUB4=GetB(detail.getString(9));
	}

	//ResultSet detail 객체의 필드 값 초기화 함수
	private void setFieldInitFromdetail(){
		detail_GRCODE="";
		detail_YEAR="";
		detail_GUBUN="";
		detail_ANNAE_SEQ=0;
		detail_ANNAE_TITLE="";
		detail_TITLE1_SUB1=0;
		detail_TITLE1_SUB2=0;
		detail_TITLE1_SUB3=0;
		detail_TITLE1_SUB4="";
	}

	//ResultSet master 객체에서 필드 값 설정 함수
	private void setFieldVariableFrommaster() throws Exception{
		master_ANNAE_GUBUN=GetB(master.getString(1));
		master_TOT_TITLE1_SUB1=master.getDouble(2);
		master_TOT_TITLE1_SUB2=master.getDouble(3);
		master_TOT_TITLE1_SUB3=master.getDouble(4);
		master_GUBUN=GetB(master.getString(5));
	}

	//ResultSet master 객체의 필드 값 초기화 함수
	private void setFieldInitFrommaster(){
		master_ANNAE_GUBUN="";
		master_TOT_TITLE1_SUB1=0;
		master_TOT_TITLE1_SUB2=0;
		master_TOT_TITLE1_SUB3=0;
		master_GUBUN="";
	}

	//ResultSet info 객체에서 필드 값 설정 함수
	private void setFieldVariableFrominfo() throws Exception{
		info_GRCODE=GetB(info.getString(1));
		info_YEAR=GetB(info.getString(2));
		info_GOAL=GetB(info.getString(3));
		info_TARGET=GetB(info.getString(4));
		info_INWON=GetB(info.getString(5));
		info_GIGAN=GetB(info.getString(6));
		info_SIGANGE=GetB(info.getString(7));
		info_SIBUNYA=GetB(info.getString(8));
		info_SISOGE=GetB(info.getString(9));
		info_SICOMMON=GetB(info.getString(10));
		info_SIJUNMUN=GetB(info.getString(11));
		info_SIETC=GetB(info.getString(12));
		info_RATEGANGE=GetB(info.getString(13));
		info_RATEBUNYA=GetB(info.getString(14));
		info_RATESOGE=GetB(info.getString(15));
		info_RATECOMMON=GetB(info.getString(16));
		info_RATEJUNMUN=GetB(info.getString(17));
		info_RATEETC=GetB(info.getString(18));
		info_YUNYOUNG=GetB(info.getString(19));
	}

	//ResultSet info 객체의 필드 값 초기화 함수
	private void setFieldInitFrominfo(){
		info_GRCODE="";
		info_YEAR="";
		info_GOAL="";
		info_TARGET="";
		info_INWON="";
		info_GIGAN="";
		info_SIGANGE="";
		info_SIBUNYA="";
		info_SISOGE="";
		info_SICOMMON="";
		info_SIJUNMUN="";
		info_SIETC="";
		info_RATEGANGE="";
		info_RATEBUNYA="";
		info_RATESOGE="";
		info_RATECOMMON="";
		info_RATEJUNMUN="";
		info_RATEETC="";
		info_YUNYOUNG="";
	}

	//ResultSet grcodenm 객체에서 필드 값 설정 함수
	private void setFieldVariableFromgrcodenm() throws Exception{
		grcodenm_GRCODENM=GetB(grcodenm.getString(1));
	}

	//ResultSet grcodenm 객체의 필드 값 초기화 함수
	private void setFieldInitFromgrcodenm(){
		grcodenm_GRCODENM="";
	}

	//-----고정 데이터 초기화 함수-----
	private void initConstVarient(){
		sheet10_A1="◈ 과  정  별  교  육  훈  련  개  요 ◈";
		sheet10_A2="과정명";
		sheet10_D2="반명";
		sheet10_B3="◎";
		sheet10_B4="◎";
		sheet10_B5="◎";
		sheet10_B6="◎";
		sheet10_B7="◎";
		sheet20_A1="교 육 편 성";
		sheet20_C2="구분";
		sheet20_D2="계";
		sheet20_E2="소양분야";
		sheet20_F2="직무분야";
		sheet20_I2="행정 및 기타";
		sheet20_F3="소 계";
		sheet20_G3="직 무 공 통";
		sheet20_H3="직 무 전 문";
		sheet20_C4="시간";
		sheet20_C5="비율";
		sheet30_A1="구분";
		sheet30_B1="과목";
		sheet30_C1="강사";
		sheet30_F1="비고";
		sheet30_C2="계";
		sheet30_D2="강의";
		sheet30_E2="참여식";
		sheet30_A3="합계";
		sheet30_B4="소계";
	}

	//-----페이지 스킵 관련 함수-----
	//페이지 스킵시 호출되는 함수로서 페이지 번호를 증가시키고 페이지 지시문 출력 그리고 Y좌표 초기화
	//매개변수에 따라 해당 쉬트의 배경 이미지, 머리글 밴드, 바닥글 밴드 함수 호출
	private void pageSkip(int nIndex) throws Exception{
		nXCurPos=nXStartPos;
		nYCurPos=nYStartPos;
		nPageNum=nPageNum+1;
		out.print("-- " + nPageNum + " PAGE --\r");

		switch(nIndex){
			case 10:		//SHEET=Sheet=1   FRAME=0에서 페이지 스킵시
			break;
		}
	}

	//페이지 스킵이 필요한지 검사하는 함수
	private boolean isPageSkip(int nTestPos){
		if(nTestPos>nYEndPos){
			return true;
		}else{
			return false;
		}
	}

	//-----공통 함수 선언-----
	private void getScriptHeader(String paper, String size, String value, String orient) throws Exception{
		out.print("--SCRIPT_START31--\r");
		out.print("PAPER=" + paper + "\r");
		out.print("PAPER_SIZE=" + size + "\r");
		out.print("PAPER_SETTING_VALUE=" + value + "\r");
		out.print("ORIENTATION=" + orient + "\r");
	}

	private void getSheetPaperInfo(String paper, String size, String value, String orient) throws Exception{
		out.print("--PAPER_INFO--\r");
		out.print("PAPER=" + paper + "\r");
		out.print("PAPER_SIZE=" + size + "\r");
		out.print("PAPER_SETTING_VALUE=" + value + "\r");
		out.print("ORIENTATION=" + orient + "\r");
	}

	private void initSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bFirstFrame){
		if(bFirstFrame){
			nStartPage=nMaxPage+1;
			nYLastPos=0;
		}
		nPageNum=nStartPage;
		nYStartPos=constStartY;
		nYEndPos=constEndY;
		nYCurPos=nYStartPos;
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
	}

	private void initChildSheetVariant(int constStartX, int constStartY, int constEndX, int constEndY, boolean bIsMultiFrame, boolean bIsFirstFrame){
		nXStartPos=constStartX;
		nXEndPos=constEndX;
		nXCurPos=nXStartPos;
		nYStartPos=constStartY;
		nYEndPos=constEndY;

		if(bIsMultiFrame){
			if(bIsFirstFrame){
				nStartPage=nPageNum;
				nYSavePos=nYCurPos;
				nYLastPos=0;
			}else{
				nPageNum=nStartPage;
				nYCurPos=nYSavePos;
			}
		}else{
			nStartPage=nPageNum;
		}
	}

	//Empty Row만으로 구성되어 출력 위치를 조정하기 위한 VoidBand 함수
	//nRangePos - VoidBand의 출력 영역
	//nIndex - PageSkip 함수 호출시 전달할 쉬트 인덱스
	private boolean voidBandNoneData(int nRangePos, int nIndex) throws Exception{
		int nTestPos;
		nTestPos=nYCurPos+nRangePos;
		if(isPageSkip(nTestPos)){
			pageSkip(nIndex);
			return true;
		}else{
			nYCurPos=nYCurPos+nRangePos;
			return false;
		}
	}

	private String Get0(String str){
		if(str==null){
			return "0";
		}else{
			if(str.equals("")){
				return "0";
			}else{
				return str;
			}
		}
	}

	private String GetB(String str){
		if(str==null){
			return "";
		}else{
			return str;
		}
	}

	private double SUM(double accVal, double tmpVal){
		return(accVal+tmpVal);
	}

	private double SUM(double accVal, long tmpVal){
		return(accVal+(double)tmpVal);
	}

	private long SUM(long accVal, long tmpVal){
		return(accVal+tmpVal);
	}

	private double SUM(long accVal, double tmpVal){
		return((double)accVal+tmpVal);
	}

	private long COUNT(long accuCNT){
		return ++accuCNT;
	}

	private long MIN(long maxV, long maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(long maxV, double maxTempV){
		if((double)maxV<=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, double maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MIN(double maxV, long maxTempV){
		if(maxV<=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}
	private long MAX(long maxV, long maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(long maxV, double maxTempV){
		if((double)maxV>=maxTempV){return (double)maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, double maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return maxTempV;}
	}

	private double MAX(double maxV, long maxTempV){
		if(maxV>=maxTempV){return maxV;}
		else{return (double)maxTempV;}
	}

	private double AVG(double sumVal, long cntVal){
		return(sumVal/cntVal);
	}

	private double AVG(long sumVal, long cntVal){
		return((double)sumVal/(double)cntVal);
	}

	private String aiReplace(String strAll, String strSrc, String strDest) {
		while(strAll.indexOf(strSrc) != -1) {
			strAll = strAll.substring(0, strAll.indexOf(strSrc)) + strDest + strAll.substring(strAll.indexOf(strSrc) + strSrc.length(), strAll.length());
		}
		return strAll;
	}

	private String toDate() {
		SimpleDateFormat dateFormat=new SimpleDateFormat("'#SERVERDATE#'yyyy/MM/dd/HH/mm/ss");
		java.util.Date currentDate = new java.util.Date();
		return dateFormat.format(currentDate);
	}

	final String toKor (String en){
		if(en==null){
			return "";
		}
		try{
			return new String(en.getBytes("8859_1"), "KSC5601");
		}catch(Exception e){return en;}
	}
	//문자의 폭을 조사하여 데이터의 출력 높이를 자동적으로 조정하는 함수
	private int getPrintHeight(String data, int[] charWidth, int fontSize, int cellWidth, int cellHeight, int nMaxHeight){
		int ch;
		int len = 95;
		int width = 0;
		int asciiWidth = 0;
		int linePitch = (int)(fontSize*1.4);
		int height = linePitch;
		int size = data.length();
		cellWidth = cellWidth-4;
		for (int i = 0; i < size; i++) {
			ch = data.charAt(i);

			if(ch<32 && !(ch==10 || ch==20 || ch==13)){
				continue;
			}

			if(ch>0x7F){
				width += asciiWidth;

				if (width > cellWidth) {
					width = asciiWidth;
					height += linePitch;
				}
				asciiWidth = 0;

				width += charWidth[len];
				if (width > cellWidth) {
					width = charWidth[len];
					height += linePitch;
				}
			} else if (ch==10 || ch==20) {
				width = 0;
				asciiWidth = 0;
				height += linePitch;
			} else if (ch==13) {
				width = 0;
				asciiWidth = 0;
				height += linePitch;
				if ((i != size-1) && (10 == (int)data.charAt(i+1))) {
					i++;
				}
			} else {
				if ((ch>64 && ch<91) || (ch>96 && ch<123)) {
					asciiWidth += charWidth[ch-32];
					if (i==size-1){
						width = width + asciiWidth;
						if (width>cellWidth){
							height += linePitch;
						}
					}
				} else {
					width += asciiWidth;

					if (width > cellWidth) {
						width = asciiWidth;
						height += linePitch;
					}

					asciiWidth = 0;

					width += charWidth[ch-32];
					if (width > cellWidth) {
						width = charWidth[ch-32];
						height += linePitch;
					}
				}
			}
		}

		if (height>cellHeight) {
			height=height-cellHeight;
		}else{
			height=0;
		}

		height = (int)MAX((long)height,(long)nMaxHeight);
		return height;
	}
}
%>
